site_name: DevOps Fundamentals

# Copyright
copyright: Copyright &copy; 2024 Mr Konsultant

theme:
  name: material
  favicon: assets/eguru_favicon.png
  logo: assets/eguru.png
  palette:
    scheme: slate
    primary: teal
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.footer
    - toc.integration
    - navigation.top
    - search.suggestions
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

nav:
  - Contents: index.md
  - Introduction: 0-introduction/
  - Networking: 1-networking/
  - Scripting: 2-scripting/
  - Version Control: 3-version-control/
  - Cloud: 4-cloud-basics/
  - CI/CD: 5-ci-cd/
  - Containerisation: 6-containerization/
  - IaaS: 7-iaas/
  - Observability: 8-observability/
  - Linux: 9-linux/

plugins:
  - search
  - literate-nav

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
